Repository KomAnw/whynot, pull requests merged in 2023-03, with the labels that each got.

#51 Feature/225 109 add sprite to tutorial
  packages/client/src/assets/images/mario-sprite2.png
  packages/client/src/assets/images/tutorial/fairycastle.png
  packages/client/src/components/Slide/Slide.tsx
  packages/client/src/components/Slide/types.ts
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Tutorial/slides/constants.ts
  packages/client/src/pages/Tutorial/slides/slides.tsx
Labels: feature, sprint-6

#53 feature/225-133-sw
  packages/client/public/sw.js
Labels: technical, sprint-7

#55 Добавил OAuth Авторизацию
  packages/client/public/sw.js
  packages/client/src/api/auth/auth.ts
  packages/client/src/api/index.ts
  packages/client/src/api/oauth/models.ts
  packages/client/src/api/oauth/oauth.ts
  packages/client/src/api/user/user.ts
  packages/client/src/assets/images/homer-lose.png
  packages/client/src/assets/images/homer-win.png
  packages/client/src/assets/images/homer404.png
  packages/client/src/assets/images/homer500.svg
  packages/client/src/components/App/App.tsx
  packages/client/src/components/App/constants.ts
  packages/client/src/components/Button/Button.tsx
  packages/client/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/client/src/components/Divider/Divider.tsx
  packages/client/src/components/Divider/index.ts
  packages/client/src/components/Divider/types.ts
  packages/client/src/components/Forms/Login/Login.tsx
  packages/client/src/components/Forms/Login/components/YandexLogo.tsx
  packages/client/src/components/GameOver/GameOver.tsx
  packages/client/src/hoc/ThemeWrapper/types.ts
  packages/client/src/index.tsx
  packages/client/src/pages/404/NotFoundPage.tsx
  packages/client/src/pages/ErrorPage/ErrorPage.tsx
  packages/client/src/pages/Game/controllers/Ground/Ground.ts
  packages/client/src/pages/OAuth/OAuth.tsx
  packages/client/src/pages/OAuth/index.ts
  packages/client/src/pages/index.ts
  packages/client/src/store/store.ts
Labels: feature, sprint-7

#59 Мелкие доработки 225-134-fixes
  packages/client/jest.config.js
  packages/client/public/images/common/background.png
  packages/client/public/images/common/chatgpt.svg
  packages/client/public/images/common/defaultAvatar.svg
  packages/client/public/images/common/editAvatar.svg
  packages/client/public/images/common/homer-lose.png
  packages/client/public/images/common/homer-win.png
  packages/client/public/images/common/homer404.png
  packages/client/public/images/common/homer500.svg
  packages/client/public/images/common/pixelDoodle.png
  packages/client/public/images/common/welcome.jpg
  packages/client/public/images/game/doodle/background.png
  packages/client/public/images/game/doodle/sprite.png
  packages/client/public/images/game/homer/background.png
  packages/client/public/images/game/homer/sprite.png
  packages/client/public/images/game/mario/background.png
  packages/client/public/images/game/mario/sprite.png
  packages/client/public/images/tutorial/fairyCastle.png
  packages/client/src/components/App/constants.ts
  packages/client/src/components/Forms/Login/Login.tsx
  packages/client/src/components/Forms/ProfileForm/ProfileForm.tsx
  packages/client/src/components/Forms/ProfileForm/styles.ts
  packages/client/src/components/Forms/consts/formsConsts.ts
  packages/client/src/components/GameOver/GameOver.tsx
  packages/client/src/components/Slide/Slide.tsx
  packages/client/src/hoc/Layout/Layout.tsx
  packages/client/src/pages/404/NotFoundPage.tsx
  packages/client/src/pages/ErrorPage/ErrorPage.tsx
  packages/client/src/pages/Tutorial/Tutorial.tsx
  packages/client/src/pages/Welcome/Welcome.tsx
  packages/client/tsconfig.json
  packages/client/vite.config.ts
Labels: sprint-7, fix

#54 Feature/225 45 local storage
  packages/client/src/components/Forms/Login/Login.tsx
  packages/client/src/components/Forms/ProfileData/ProfileData.tsx
  packages/client/src/components/Forms/Registration/Registration.tsx
  packages/client/src/utils/storage.ts
Labels: feature, sprint-7

#58 Feature/225 113 add more one browser api
  packages/client/src/components/GameOver/GameOver.tsx
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Game/controllers/Gamepad/Gamepad.ts
  packages/client/src/pages/Game/controllers/Player/Player.ts
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Settings/gamepadSlice.ts
  packages/client/src/store/store.ts
Labels: feature, sprint-7

#56 Feature/225 25 leaderboard api
  packages/client/src/api/leaderboard/leaderboard.ts
  packages/client/src/api/leaderboard/models.ts
  packages/client/src/components/LeaderboardRow/type.ts
  packages/client/src/pages/Game/components/GameResult/GameResult.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
  packages/client/src/store/store.ts
Labels: feature, sprint-7

#62 Feature/225 137
  packages/client/src/components/LeaderboardRow/LeaderboardRow.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Tutorial/Tutorial.tsx
Labels: sprint-7, fix

#61 feature/ssr-routing
  packages/client/index.html
  packages/client/package.json
  packages/client/src/api/index.ts
  packages/client/src/hoc/Layout/Layout.tsx
  packages/client/src/index.css
  packages/client/src/utils/globalPolyfill.ts
  packages/client/ssr.tsx
  packages/server/configs/development.ts
  packages/server/configs/production.ts
  packages/server/index.ts
  yarn.lock
Labels: feature, sprint-7

#69 Feature/game result hero mode
  packages/client/public/images/common/homer-lose.png
  packages/client/public/images/common/homer-win.png
  packages/client/public/images/game/doodle/doodle-lose.png
  packages/client/public/images/game/doodle/doodle-win.png
  packages/client/public/images/game/homer/homer-lose.png
  packages/client/public/images/game/homer/homer-win.png
  packages/client/public/images/game/mario/mario-lose.png
  packages/client/public/images/game/mario/mario-win.png
  packages/client/src/components/App/constants.ts
  packages/client/src/components/GameOver/GameOver.tsx
  packages/client/src/components/GameOver/types.ts
  packages/client/src/pages/Game/types/types.ts
  packages/server/state/mode.ts
Labels: sprint-7, sprint-8, fix

#65 Feature/225 127 page forum
  packages/client/public/images/forum/emoji1.png
  packages/client/public/images/forum/emoji2.png
  packages/client/public/images/forum/emoji3.png
  packages/client/public/sw.js
  packages/client/src/components/App/GlobalStyles.ts
  packages/client/src/components/App/constants.ts
  packages/client/src/components/Forms/ProfileAvatar/ProfileAvatar.tsx
  packages/client/src/components/Forms/ProfileAvatar/types.ts
  packages/client/src/components/Forms/ProfileForm/ProfileForm.tsx
  packages/client/src/components/Forms/ProfileForm/constants.ts
  packages/client/src/components/Input/Input.tsx
  packages/client/src/components/Input/__snapshots__/Input.test.tsx.snap
  packages/client/src/components/Input/type.ts
  packages/client/src/hoc/Layout/Layout.tsx
  packages/client/src/hoc/ThemeWrapper/types.ts
  packages/client/src/pages/Forum/Forum.tsx
  packages/client/src/pages/Forum/Routes.tsx
  packages/client/src/pages/Forum/components/IconButtonEmoji.tsx
  packages/client/src/pages/Forum/components/IconButtonSend.tsx
  packages/client/src/pages/Forum/components/IconPost.tsx
  packages/client/src/pages/Forum/pages/FormPost/FormPost.tsx
  packages/client/src/pages/Forum/pages/FormPost/components/MenuEmojis/MenuEmojis.tsx
  packages/client/src/pages/Forum/pages/FormPost/components/MenuEmojis/index.ts
  packages/client/src/pages/Forum/pages/FormPost/components/MessageElement/EmojiBox/EmojiBox.tsx
  packages/client/src/pages/Forum/pages/FormPost/components/MessageElement/EmojiBox/index.ts
  packages/client/src/pages/Forum/pages/FormPost/components/MessageElement/MessageElement.tsx
  packages/client/src/pages/Forum/pages/FormPost/components/MessageElement/index.ts
  packages/client/src/pages/Forum/pages/FormPost/components/MessageInput/MessageInput.tsx
  packages/client/src/pages/Forum/pages/FormPost/components/MessageInput/index.ts
  packages/client/src/pages/Forum/pages/FormPost/demoData.ts
  packages/client/src/pages/Forum/pages/FormPost/index.ts
  packages/client/src/pages/Forum/pages/FormPost/utils/emojiLinkIcon.ts
  packages/client/src/pages/Forum/pages/FormPost/utils/sortMessage.ts
  packages/client/src/pages/Forum/pages/ForumPosts/ForumPosts.tsx
  packages/client/src/pages/Forum/pages/ForumPosts/components/PostElement/PostElement.tsx
  packages/client/src/pages/Forum/pages/ForumPosts/components/PostElement/index.ts
  packages/client/src/pages/Forum/pages/ForumPosts/components/PostsInput/PostsInput.tsx
  packages/client/src/pages/Forum/pages/ForumPosts/components/PostsInput/index.ts
  packages/client/src/pages/Forum/pages/ForumPosts/demoData.ts
  packages/client/src/pages/Forum/pages/ForumPosts/index.ts
  packages/client/src/pages/Forum/pages/types.ts
  yarn.lock
Labels: feature, sprint-7

#71 added sound to game
  .eslintrc.js
  packages/client/public/media/sound.mp3
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Settings/soundSlice.ts
  packages/client/src/store/store.ts
Labels: feature, sprint-8

#73 new server structure
  packages/client/src/ssr.tsx
  packages/server/configs/development.ts
  packages/server/configs/production.ts
  packages/server/package.json
  packages/server/src/app.ts
  packages/server/src/db.ts
  packages/server/src/server.ts
  packages/server/src/ssr/configs/development.ts
  packages/server/src/ssr/configs/production.ts
  packages/server/src/ssr/index.ts
  packages/server/src/ssr/state/index.ts
  packages/server/src/ssr/state/mode.ts
  packages/server/src/ssr/state/state.d.ts
  packages/server/src/ssr/state/theme.ts
Labels: technical, sprint-8

#70 Feature/225 155 connect postgresql
  .env.sample
  packages/server/database/postgres.ts
  packages/server/package.json
  packages/server/src/db.ts
  packages/server/tsconfig.json
  packages/server/utils/findFile.ts
Labels: technical, sprint-8

#74 Написан мидлвар авторизации.
  packages/client/src/api/auth/auth.ts
  packages/client/src/api/common/consts/apiConsts.ts
  packages/client/src/api/common/utils/apiUtilts.ts
  packages/client/src/api/index.ts
  packages/client/src/api/leaderboard/leaderboard.ts
  packages/client/src/api/oauth/oauth.ts
  packages/client/src/api/user/user.ts
  packages/client/src/components/Forms/ProfileForm/ProfileForm.tsx
  packages/server/database/postgres.ts
  packages/server/middlewares/auth.ts
  packages/server/package.json
  packages/server/src/app.ts
  packages/server/src/ssr/index.ts
  yarn.lock
Labels: feature, sprint-8

#76 Feature/225 146 1 create model db posts and messages
  packages/server/database/postgres.ts
  packages/server/models/message.ts
  packages/server/models/post.ts
  packages/server/package.json
  packages/server/src/app.ts
  yarn.lock
Labels: feature, sprint-8
