Repository KomAnw/whynot, pull requests merged in 2023-02, with the labels that each got.

#1 initial project setup
  packages/client/index.html
  packages/client/package.json
  packages/client/src/App.css
  packages/client/src/App.tsx
  packages/client/src/GlobalStyles.ts
  packages/client/src/components/App/App.test.tsx
  packages/client/src/components/App/App.tsx
  packages/client/src/components/TestComponent/TestComponent.tsx
  packages/client/src/index.css
  packages/client/src/index.tsx
  packages/client/src/main.tsx
  packages/client/tsconfig.json
  packages/client/vite.config.ts
  yarn.lock
Labels: sprint-5, feature

#2 Technical/225-60-config
  .eslintignore
  .eslintrc.js
  packages/client/jest.config.js
  packages/client/package.json
  packages/client/src/GlobalStyles.ts
  packages/client/src/client.d.ts
  packages/client/src/components/App/App.test.tsx
  packages/client/src/components/App/App.tsx
  packages/client/src/components/TestComponent/TestComponent.tsx
  packages/client/src/index.tsx
  packages/client/tsconfig.json
  packages/server/__tests__/example.test.ts
  packages/server/db.ts
  packages/server/index.ts
  packages/server/jest.config.js
  packages/server/package.json
  yarn.lock
Labels: sprint-5, technical

#5 Feature/225-11-routing
  .eslintrc.js
  packages/client/src/components/App/App.tsx
  packages/client/src/components/App/constants.ts
  packages/client/src/hoc/Layout/Layout.tsx
  packages/client/src/hoc/Layout/index.ts
  packages/client/src/hoc/PrivateRoute/PrivateRoute.tsx
  packages/client/src/hoc/PrivateRoute/index.ts
  packages/client/src/index.tsx
  packages/client/src/pages/404/404.tsx
  packages/client/src/pages/404/index.ts
  packages/client/src/pages/500/500.tsx
  packages/client/src/pages/500/index.ts
  packages/client/src/pages/SignIn/SignIn.tsx
  packages/client/src/pages/SignIn/index.ts
  packages/client/src/pages/SignUp/SignUp.tsx
  packages/client/src/pages/SignUp/index.ts
  packages/client/src/pages/Welcome/Welcome.tsx
  packages/client/src/pages/Welcome/index.ts
  packages/client/src/pages/index.ts
  packages/client/tsconfig.json
  packages/client/vite.config.ts
Labels: sprint-5, feature

#4 Feature/225 56 input component
  packages/client/src/components/Input/Input.tsx
  packages/client/src/components/Input/index.ts
  packages/client/src/components/Input/type.ts
  yarn.lock
Labels: sprint-5, feature

#20 Feature/background
  packages/client/src/assets/images/background.png
  packages/client/src/hoc/Layout/Layout.tsx
Labels: sprint-5, feature

#15 Feature/225-2 Аутентификация и Авторизация
  packages/client/src/api/auth/auth.ts
  packages/client/src/api/auth/models.ts
  packages/client/src/api/index.ts
  packages/client/src/components/App/App.tsx
  packages/client/src/components/Switch/Switch.tsx
  packages/client/src/hoc/Layout/Layout.tsx
  packages/client/src/hoc/PrivateRoute/PrivateRoute.tsx
  packages/client/src/hoc/ThemeWrapper/ThemeWrapper.tsx
  packages/client/src/hooks/redux/index.ts
  packages/client/src/pages/Game.tsx
  packages/client/src/pages/SignIn/SignIn.tsx
  packages/client/src/pages/Welcome/Welcome.tsx
  packages/client/src/store/store.ts
  packages/client/vite.config.ts
Labels: sprint-5, feature

#6 225-15-registration-page
  packages/client/src/GlobalStyles.ts
  packages/client/src/components/App/App.tsx
  packages/client/src/components/App/constants.ts
  packages/client/src/components/Button/types.ts
  packages/client/src/components/Forms/Registration/Registration.tsx
  packages/client/src/components/Forms/Registration/consts/RegistrationConsts.ts
  packages/client/src/components/Input/Input.tsx
  packages/client/src/components/Input/index.ts
  packages/client/src/components/Input/type.ts
  packages/client/src/components/Link/Link.tsx
  packages/client/src/components/Link/index.ts
  packages/client/src/components/Link/type.ts
  packages/client/src/hoc/Layout/Layout.tsx
  packages/client/src/hoc/ThemeWrapper/types.ts
  packages/client/src/pages/404/NotFoundPage.tsx
  packages/client/src/pages/404/index.ts
  packages/client/src/pages/ErrorPage/ErrorPage.tsx
  packages/client/src/pages/SignUp/SignUp.tsx
  packages/client/src/pages/Welcome/Welcome.tsx
  packages/client/src/utils/validation.ts
Labels: sprint-5, feature

#14 Feature/225 4 leaderboard
  packages/client/src/components/App/App.tsx
  packages/client/src/components/App/constants.ts
  packages/client/src/components/LeaderboardRow/LeaderboardRow.tsx
  packages/client/src/components/LeaderboardRow/consts/leaderboardConsts.ts
  packages/client/src/components/LeaderboardRow/index.ts
  packages/client/src/components/LeaderboardRow/type.ts
  packages/client/src/design/H1.tsx
  packages/client/src/design/ListText.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
  packages/client/src/pages/Leaderboard/index.ts
  packages/client/src/pages/index.ts
Labels: sprint-5, feature

#11 Feature/225 1 signin page
  packages/client/src/components/Forms/Login/Login.tsx
  packages/client/src/components/Forms/Login/consts/LoginConsts.ts
  packages/client/src/components/Forms/Login/index.ts
  packages/client/src/pages/SignIn/SignIn.tsx
Labels: sprint-5, feature

#28 Feature/225 84 game over component
  packages/client/src/assets/images/gomer-lose.png
  packages/client/src/assets/images/gomer-win.png
  packages/client/src/components/GameOver/GameOver.tsx
  packages/client/src/components/GameOver/index.ts
  packages/client/src/components/GameOver/types.ts
  packages/client/src/design/H3.tsx
  packages/client/src/design/Text.tsx
Labels: sprint-5, feature

#31 feature/225-83-game
  .eslintrc.js
  packages/client/src/hooks/react/index.ts
  packages/client/src/index.tsx
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Game/controllers/Ground/Ground.ts
  packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
  packages/client/src/pages/Game/controllers/Player/Player.ts
  packages/client/src/pages/Game/types/types.ts
  packages/client/src/pages/Welcome/Welcome.tsx
Labels: sprint-5, feature, sprint-6

#30 Feature/225 85 profile api
  packages/client/src/api/auth/auth.ts
  packages/client/src/api/auth/models.ts
  packages/client/src/api/user/models.ts
  packages/client/src/api/user/user.ts
  packages/client/src/components/Forms/Login/Login.tsx
  packages/client/src/components/Forms/Login/consts/LoginConsts.ts
  src/index.tsx
Labels: sprint-5, feature, sprint-6

#45 Feature/225 102 sw
  packages/client/package.json
  packages/client/src/assets/.keep
  packages/client/src/assets/fonts/Handjet.ttf
  packages/client/src/assets/fonts/Handjet.woff2
  packages/client/src/client.d.ts
  packages/client/src/components/App/constants.ts
  packages/client/src/components/Button/Button.tsx
  packages/client/src/components/Link/Link.tsx
  packages/client/src/index.tsx
  packages/client/src/utils/workers.ts
  packages/client/sw.js
  yarn.lock
Labels: feature, sprint-6

#50 added checkboxed to Settings page
  packages/client/src/assets/images/game/doodle/background.png
  packages/client/src/assets/images/game/doodle/sprite.png
  packages/client/src/assets/images/game/homer/background.png
  packages/client/src/assets/images/game/homer/sprite.png
  packages/client/src/components/App/constants.ts
  packages/client/src/components/Switch/Switch.tsx
  packages/client/src/hoc/Layout/Layout.tsx
  packages/client/src/pages/Game/modeSlice.ts
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Settings/fullscreenSlice.ts
  packages/client/src/store/store.ts
  packages/client/src/utils/fullscreenApi.ts
Labels: feature, sprint-6

#44 Feature/225 99 sprite changing
  packages/client/src/assets/images/game/doodle/background.png
  packages/client/src/assets/images/game/doodle/sprite.png
  packages/client/src/assets/images/game/gomer/sprite.png
  packages/client/src/assets/images/game/homer/background.png
  packages/client/src/assets/images/game/homer/sprite.png
  packages/client/src/assets/images/game/mario/sprite.png
  packages/client/src/components/App/constants.ts
  packages/client/src/components/Switch/Switch.tsx
  packages/client/src/hoc/Layout/Layout.tsx
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Game/controllers/Player/Player.ts
  packages/client/src/pages/Game/modeSlice.ts
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Settings/fullscreenSlice.ts
  packages/client/src/store/store.ts
  packages/client/src/utils/fullscreenApi.ts
Labels: feature, sprint-6

#43 Feature/225 98 sprite
  .gitignore
  packages/client/.gitignore
  packages/client/src/assets/images/game/doodle/background.png
  packages/client/src/assets/images/game/doodle/sprite.png
  packages/client/src/assets/images/game/homer/background.png
  packages/client/src/assets/images/game/homer/sprite.png
  packages/client/src/assets/images/game/mario/background.png
  packages/client/src/assets/images/game/mario/sprite.png
  packages/client/src/assets/images/mario-sprite2.png
  packages/client/src/components/App/constants.ts
  packages/client/src/components/Forms/Login/Login.tsx
  packages/client/src/components/Switch/Switch.tsx
  packages/client/src/hoc/Layout/Layout.tsx
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Game/controllers/Ground/Ground.ts
  packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
  packages/client/src/pages/Game/controllers/Player/Player.ts
  packages/client/src/pages/Game/modeSlice.ts
  packages/client/src/pages/Game/types/types.ts
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Settings/fullscreenSlice.ts
  packages/client/src/store/store.ts
  packages/client/src/utils/fullscreenApi.ts
Labels: feature, sprint-6
