Repository KomAnw/whynot, pull requests merged in 2023-04, with the labels that each got.

#79 Добавить CSP (Content-Security-Policy)
  packages/server/middlewares/auth.ts
  packages/server/middlewares/index.ts
  packages/server/package.json
  packages/server/src/app.ts
  packages/server/src/ssr/index.ts
  yarn.lock
Labels: technical, sprint-8

#77 Feature/add platform types
  .eslintrc.js
  packages/client/public/images/game/homer/sprite.png
  packages/client/public/images/game/mario/sprite.png
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Game/controllers/Platforms/Platforms.ts
  packages/client/src/pages/Game/controllers/Player/Player.ts
Labels: feature, sprint-8

#78 Feature/225 150 controller router post
  packages/server/controllers/posts/index.ts
  packages/server/controllers/posts/posts.ts
  packages/server/controllers/type.ts
  packages/server/middlewares/index.ts
  packages/server/models/message.ts
  packages/server/models/post.ts
  packages/server/package.json
  packages/server/routes/index.ts
  packages/server/routes/posts/index.ts
  packages/server/routes/posts/posts.ts
  packages/server/src/app.ts
  yarn.lock
Labels: feature, sprint-8

#80 feature/225-160-Controller-Router-Message
  packages/server/controllers/messages/index.ts
  packages/server/controllers/messages/messages.ts
  packages/server/controllers/type.ts
  packages/server/controllers/utils/sortMessages.ts
  packages/server/models/message.ts
  packages/server/routes/index.ts
  packages/server/routes/messages/index.ts
  packages/server/routes/messages/messages.ts
Labels: feature, sprint-8

#85 225-166-fixes
  packages/client/src/api/common/consts/apiConsts.ts
  packages/client/src/components/Forms/Login/Login.tsx
  packages/client/src/components/Forms/ProfileAvatar/ProfileAvatar.tsx
  packages/client/src/components/Forms/ProfileData/ProfileData.tsx
  packages/client/src/components/Forms/ProfileForm/constants.ts
  packages/client/src/components/Forms/ProfileForm/styles.ts
  packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
  packages/client/src/components/Forms/Registration/Registration.tsx
  packages/client/src/pages/Forum/pages/FormPost/FormPost.tsx
  packages/client/src/pages/Forum/pages/FormPost/components/MessageInput/MessageInput.tsx
  packages/client/src/pages/Forum/pages/ForumPosts/ForumPosts.tsx
  packages/client/src/pages/Forum/pages/ForumPosts/components/PostsInput/PostsInput.tsx
  packages/client/src/pages/Game/components/GameResult/GameResult.tsx
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Tutorial/Tutorial.tsx
  packages/client/src/pages/Welcome/Welcome.tsx
  packages/client/src/utils/logger.ts
  packages/client/src/utils/workers.ts
  packages/client/vite.config.ts
  packages/server/database/postgres.ts
  packages/server/src/app.ts
  packages/server/src/server.ts
  packages/server/src/ssr/index.ts
  packages/server/utils/logger.ts
Labels: sprint-8, fix

#87 prepared messages api
  packages/client/src/api/forum/messages/messages.ts
  packages/client/src/api/forum/messages/models.ts
  packages/client/src/api/forum/posts/models.ts
  packages/client/src/api/forum/posts/posts.ts
  packages/client/src/store/store.ts
  packages/server/controllers/messages/index.ts
  packages/server/controllers/messages/messages.ts
  packages/server/controllers/type.ts
  packages/server/models/message.ts
  packages/server/routes/messages/messages.ts
  packages/server/routes/posts/posts.ts
Labels: feature, sprint-8

#90 225-146-1-connection-Api-and-pagePosts
  .env.sample
  packages/client/src/api/forum/posts/posts.ts
  packages/client/src/pages/Forum/pages/ForumPosts/ForumPosts.tsx
  packages/client/src/pages/Forum/pages/ForumPosts/components/PostElement/PostElement.tsx
  packages/client/src/pages/Forum/pages/ForumPosts/components/PostsInput/PostsInput.tsx
  packages/client/src/pages/Forum/pages/ForumPosts/demoData.ts
  packages/server/controllers/posts/posts.ts
  packages/server/controllers/type.ts
Labels: feature, sprint-8

#94 Feature/225 169
  MEMORYLEAKS.md
Labels: feature, sprint-9

#96 Feature/docker
  .env.sample
  Dockerfile.client
  Dockerfile.server
  docker-compose.yml
  package.json
  packages/client/nginx.conf
  packages/client/package.json
  packages/client/src/pages/Forum/pages/ForumPost/components/MessageElement/MessageElement.tsx
  packages/server/__tests__/example.test.ts
  packages/server/database/postgres.ts
  packages/server/middlewares/index.ts
  packages/server/package.json
  packages/server/src/app.ts
  packages/server/src/server.ts
  packages/server/src/ssr/configs/production.ts
  packages/server/utils/findFile.ts
  yarn.lock
Labels: feature, sprint-9

#99 Feature/225 175 update readme
  README.md
Labels: technical, sprint-9

#97 Возвращен сервис воркер
  packages/client/src/index.tsx
Labels: technical, work in progress, sprint-9

#102 Feature/docker nginx https
  Dockerfile.client
  docker-compose.yml
  packages/client/.gitignore
  packages/client/nginx.conf
  packages/client/src/api/common/consts/apiConsts.ts
  packages/client/src/api/oauth/oauth.ts
  packages/client/src/components/App/constants.ts
  packages/client/src/components/Forms/ProfilePassword/ProfilePassword.tsx
  packages/client/src/components/Forms/consts/formsConsts.ts
  packages/server/middlewares/index.ts
Labels: feature, sprint-9
